services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: cc_server
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: dummy_secret_key
    ports:
      - "3000:3000"
    volumes:
      - server_db:/app/db
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: cc_client
    depends_on:
      - server
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  server_db:
